	LIST	P=PIC16F84A
	INCLUDE	"P16F84A.INC"
		
	__CONFIG    _HS_OSC&_WDT_OFF
		
CNT1	EQU	    0CH
CNT2	EQU	    0DH
CNT3	EQU	    0EH
MY_CNT1 EQU	    10H
MY_CNT2 EQU	    11H
MY_CNT3 EQU	    12H
MY_CNT4 EQU	    13H
MY_CNT5 EQU	    14H
MY_CNT6	EQU	    15H
MY_CNT7 EQU	    16H
MY_CNT8	EQU	    17H
MY_CNT9 EQU	    18H
MY_CNT10 EQU	    19H

	ORG	    0H

MAIN	
	BSF	    STATUS , RP0
	CLRF	    TRISB
	BCF	    STATUS , RP0
	GOTO	    MAINLP
	
MAINLP
	CALL	    D5_8
	CALL	    DELAY_16
	CALL	    D5_16
	CALL	    MYTIMEOUT2
	CALL	    D5_4
	CALL	    G5_8
	CALL	    DELAY_16
	CALL	    G5_16
	CALL	    MYTIMEOUT2
	CALL	    G5_4
	CALL	    B5_8
	CALL	    DELAY_16
	CALL	    B5_16
	CALL	    MYTIMEOUT2
	CALL	    B5_4
	CALL	    A5_4
	CALL	    MYTIMEOUT2
	CALL	    A5_4
	
	CALL	    DELAY_4
	
	CALL	    D5_8
	CALL	    DELAY_16
	CALL	    D5_16
	CALL	    MYTIMEOUT2
	CALL	    D5_4
	CALL	    MYTIMEOUT2
	CALL	    D5_32
	CALL	    DELAY_16
	CALL	    A5_8
	CALL	    MYTIMEOUT2
	CALL	    A5_8
	CALL	    MYTIMEOUT2
	CALL	    A5_4
	CALL	    MYTIMEOUT2
	CALL	    A5_32
	CALL	    C6_4
	CALL	    MYTIMEOUT2
	CALL	    C6_4
	CALL	    B5_8
	CALL	    MYTIMEOUT2
	CALL	    B5_8
	CALL	    B5_4
	CALL	    A5_4
	CALL	    MYTIMEOUT2
	CALL	    A5_4
	CALL	    G5_4
	CALL	    FS5_4
	CALL	    G5_4
	CALL	    MYTIMEOUT1
	CALL	    B5_4
	CALL	    A5_4
	CALL	    MYTIMEOUT2
	CALL	    A5_4
	CALL	    G5_4
	CALL	    MYTIMEOUT2
	CALL	    G5_4 ;2
	CALL	    G5_4 ;2
	CALL	    FS5_4
	CALL	    E5_4
	CALL	    MYTIMEOUT1
	CALL	    D5_4
	CALL	    D5_8
	
	CALL	    DELAY_8
	CALL	    DELAY_4
	
	CALL	    D5_8
	CALL	    DELAY_16
	CALL	    D5_16
	CALL	    MYTIMEOUT2
	CALL	    D5_4
	CALL	    G5_8
	CALL	    DELAY_16
	CALL	    G5_16
	CALL	    MYTIMEOUT2
	CALL	    G5_4
	CALL	    B5_8
	CALL	    DELAY_16
	CALL	    B5_16
	CALL	    MYTIMEOUT2
	CALL	    B5_4
	CALL	    A5_4
	CALL	    MYTIMEOUT2
	CALL	    A5_4
	CALL	    MYTIMEOUT2
	
	CALL	    DELAY_4
	
	CALL	    D5_8
	CALL	    DELAY_16
	CALL	    D5_16
	CALL	    D5_4
	CALL	    D5_32
	CALL	    DELAY_16
	CALL	    A5_8
	CALL	    A5_8
	CALL	    A5_4
	CALL	    A5_32
	CALL	    C6_4
	CALL	    C6_4
	CALL	    B5_8
	CALL	    B5_8
	CALL	    B5_4
	CALL	    A5_4
	CALL	    A5_4
	CALL	    G5_4
	CALL	    FS5_4
	CALL	    G5_4
	CALL	    B5_4
	CALL	    A5_4
	CALL	    A5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    FS5_4
	CALL	    G5_4
	CALL	    A5_4
	CALL	    A5_4
	CALL	    B5_4
	CALL	    B5_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    FS5_4
	CALL	    E5_4
	CALL	    D5_4
	CALL	    C5_4
	CALL	    D5_4
	CALL	    B5_L_8 ;2*8
	CALL	    B5_L_8 ;2*8
	CALL	    A5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    A5_4
	CALL	    B5_4
	CALL	    C6_4
	CALL	    C6_4
	CALL	    E5_4
	CALL	    DELAY_16
	CALL	    G5_8
	CALL	    G5_8
	CALL	    G5_4
	CALL	    G5_4
	CALL	    FS5_4
	CALL	    FS5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    G5_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    DELAY_4
	CALL	    DELAY_4
		
	GOTO       MAINLP
	
C5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    C5_4_LOOP
	RETURN	
C5_4_LOOP
	CALL	    C5_16
	DECFSZ	    MY_CNT6,F
	GOTO	    C5_4_LOOP
	RETURN	
CS5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    CS5_4_LOOP
	RETURN	
CS5_4_LOOP
	CALL	    CS5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    CS5_4_LOOP	
	RETURN	
D5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    D5_4_LOOP
	RETURN	
D5_4_LOOP
	CALL	    D5_16  
	DECFSZ	    MY_CNT6,F
	GOTO	    D5_4_LOOP	
	RETURN	
DS5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    DS5_4_LOOP
	RETURN	
DS5_4_LOOP
	CALL	    DS5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    DS5_4_LOOP	
	RETURN	
E5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    E5_4_LOOP
	RETURN	
E5_4_LOOP
	CALL	    E5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    E5_4_LOOP	
	RETURN	
F5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    F5_4_LOOP
	RETURN	
F5_4_LOOP
	CALL	    F5_16  
	DECFSZ	    MY_CNT6,F
	GOTO	    F5_4_LOOP	
	RETURN	
FS5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    FS5_4_LOOP
	RETURN	
FS5_4_LOOP
	CALL	    FS5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    FS5_4_LOOP	
	RETURN	
G5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    G5_4_LOOP
	RETURN	
G5_4_LOOP
	CALL	    G5_16 
	DECFSZ	    MY_CNT6,F
	GOTO	    G5_4_LOOP	
	RETURN	
GS5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    GS5_4_LOOP
	RETURN	
GS5_4_LOOP
	CALL	    GS5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    GS5_4_LOOP	
	RETURN	
A5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    A5_4_LOOP
	RETURN	
A5_4_LOOP
	CALL	    A5_16  
	DECFSZ	    MY_CNT6,F
	GOTO	    A5_4_LOOP	
	RETURN	
AS5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    AS5_4_LOOP
	RETURN	
AS5_4_LOOP
	CALL	    AS5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    AS5_4_LOOP	
	RETURN	
B5_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    B5_4_LOOP
	RETURN	
B5_4_LOOP
	CALL	    B5_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    B5_4_LOOP	
	RETURN	
C6_4
	MOVLW	    004H
	MOVWF	    MY_CNT6
	CALL	    C6_4_LOOP
	RETURN	
C6_4_LOOP
	CALL	    C6_16   
	DECFSZ	    MY_CNT6,F
	GOTO	    C6_4_LOOP	
	RETURN		

C5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    C5_8_LOOP
	RETURN	
C5_8_LOOP
	CALL	    C5_16
	DECFSZ	    MY_CNT7,F
	GOTO	    C5_8_LOOP
	RETURN	
CS5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    CS5_8_LOOP
	RETURN	
CS5_8_LOOP
	CALL	    CS5_16  
	DECFSZ	    MY_CNT7,F
	GOTO	    CS5_8_LOOP	
	RETURN	
D5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    D5_8_LOOP
	RETURN	
D5_8_LOOP
	CALL	    D5_16 
	DECFSZ	    MY_CNT7,F
	GOTO	    D5_8_LOOP	
	RETURN	
DS5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    DS5_8_LOOP
	RETURN	
DS5_8_LOOP
	CALL	    DS5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    DS5_8_LOOP	
	RETURN	
E5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    E5_8_LOOP
	RETURN	
E5_8_LOOP
	CALL	    E5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    E5_8_LOOP	
	RETURN	
F5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    F5_8_LOOP
	RETURN	
F5_8_LOOP
	CALL	    F5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    F5_8_LOOP	
	RETURN	
FS5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    FS5_8_LOOP
	RETURN	
FS5_8_LOOP
	CALL	    FS5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    FS5_8_LOOP	
	RETURN
G5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    G5_8_LOOP
	RETURN	
G5_8_LOOP
	CALL	    G5_16  
	DECFSZ	    MY_CNT7,F
	GOTO	    G5_8_LOOP	
	RETURN	
GS5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    GS5_8_LOOP
	RETURN	
GS5_8_LOOP
	CALL	    GS5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    GS5_8_LOOP	
	RETURN	
A5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    A5_8_LOOP
	RETURN	
A5_8_LOOP
	CALL	    A5_16  
	DECFSZ	    MY_CNT7,F
	GOTO	    A5_8_LOOP	
	RETURN	
AS5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    AS5_8_LOOP
	RETURN	
AS5_8_LOOP
	CALL	    AS5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    AS5_8_LOOP	
	RETURN	
B5_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    B5_8_LOOP
	RETURN	
B5_8_LOOP
	CALL	    B5_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    B5_8_LOOP	
	RETURN	
	
C6_8
	MOVLW	    002H
	MOVWF	    MY_CNT7
	CALL	    C6_8_LOOP
	RETURN	
C6_8_LOOP
	CALL	    C6_16   
	DECFSZ	    MY_CNT7,F
	GOTO	    C6_8_LOOP	
	RETURN

B5_L_8
	MOVLW	    053H
	MOVWF	    MY_CNT5
	CALL	    B5_L_8_LOOP
	RETURN	
B5_L_8_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    B5_L
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    B5_L	    
	DECFSZ	    MY_CNT5,F
	GOTO	    B5_L_8_LOOP	
	RETURN	
	
C6_16
	MOVLW	    058H
	MOVWF	    MY_CNT5
	CALL	    C6_16_LOOP
	RETURN	
C6_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    C6
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    C6	    
	DECFSZ	    MY_CNT5,F
	GOTO	    C6_16_LOOP	
	RETURN	
	
B5_16
	MOVLW	    053H
	MOVWF	    MY_CNT5
	CALL	    B5_16_LOOP
	RETURN	
B5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    B5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    B5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    B5_16_LOOP	
	RETURN	
AS5_16
	MOVLW	    04FH
	MOVWF	    MY_CNT5
	CALL	    AS5_16_LOOP
	RETURN	
AS5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    AS5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    AS5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    AS5_16_LOOP	
	RETURN	
A5_16
	MOVLW	    04AH
	MOVWF	    MY_CNT5
	CALL	    A5_16_LOOP
	RETURN	
A5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    A5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    A5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    A5_16_LOOP	
	RETURN	
GS5_16
	MOVLW	    046H
	MOVWF	    MY_CNT5
	CALL	    GS5_16_LOOP
	RETURN	
GS5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    GS5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    GS5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    GS5_16_LOOP	
	RETURN	
G5_16
	MOVLW	    042H
	MOVWF	    MY_CNT5
	CALL	    G5_16_LOOP
	RETURN	
G5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    G5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    G5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    G5_16_LOOP	
	RETURN	
FS5_16
	MOVLW	    03EH
	MOVWF	    MY_CNT5
	CALL	    FS5_16_LOOP
	RETURN	
FS5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    FS5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    FS5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    FS5_16_LOOP	
	RETURN	
F5_16
	MOVLW	    03BH
	MOVWF	    MY_CNT5
	CALL	    F5_16_LOOP
	RETURN	
F5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    F5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    F5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    F5_16_LOOP	
	RETURN	
E5_16
	MOVLW	    038H
	MOVWF	    MY_CNT5
	CALL	    E5_16_LOOP
	RETURN	
E5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    E5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    E5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    E5_16_LOOP	
	RETURN	
DS5_16
	MOVLW	    034H
	MOVWF	    MY_CNT5
	CALL	    DS5_16_LOOP
	RETURN	
DS5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    DS5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    DS5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    DS5_16_LOOP	
	RETURN	
D5_16
	MOVLW	    031H
	MOVWF	    MY_CNT5
	CALL	    D5_16_LOOP
	RETURN	
D5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    D5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    D5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    D5_16_LOOP	
	RETURN	
CS5_16
	MOVLW	    02FH
	MOVWF	    MY_CNT5
	CALL	    CS5_16_LOOP
	RETURN	
CS5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    CS5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    CS5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    CS5_16_LOOP	
	RETURN	
C5_16
	MOVLW	    02CH
	MOVWF	    MY_CNT5
	CALL	    C5_16_LOOP
	RETURN	
C5_16_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    C5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    C5	    
	DECFSZ	    MY_CNT5,F
	GOTO	    C5_16_LOOP	
	RETURN	
	
B5_L
	MOVLW	    002H
	MOVWF	    MY_CNT4
	CALL	    B5_L_LOOP
	RETURN	
B5_L_LOOP
	CALL	    B5
	DECFSZ	    MY_CNT4,F	
	GOTO	    B5_L_LOOP	
	RETURN	
AS5_L
	MOVLW	    002H
	MOVWF	    MY_CNT4
	CALL	    B5_L_LOOP
	RETURN	
AS5_L_LOOP
	CALL	    AS5
	DECFSZ	    MY_CNT4,F	
	GOTO	    B5_L_LOOP	
	RETURN	
;A5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    A5_L_LOOP
;	RETURN	
;A5_L_LOOP
;	CALL	    A5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    A5_L_LOOP	
;	RETURN	
;GS5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    GS5_L_LOOP
;	RETURN	
;GS5_L_LOOP
;	CALL	    GS5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    GS5_L_LOOP	
;	RETURN	
;G5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    G5_L_LOOP
;	RETURN	
;G5_L_LOOP
;	CALL	    G5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    G5_L_LOOP	
;	RETURN	
;FS5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    FS5_L_LOOP
;	RETURN	
;FS5_L_LOOP
;	CALL	    FS5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    FS5_L_LOOP	
;	RETURN	
;F5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    F5_L_LOOP
;	RETURN	
;F5_L_LOOP
;	CALL	    F5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    F5_L_LOOP	
;	RETURN	
;E5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    E5_L_LOOP
;	RETURN	
;E5_L_LOOP
;	CALL	    E5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    E5_L_LOOP	
;	RETURN	
;DS5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    DS5_L_LOOP
;	RETURN	
;DS5_L_LOOP
;	CALL	    DS5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    DS5_L_LOOP	
;	RETURN	
;D5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    D5_L_LOOP
;	RETURN	
;D5_L_LOOP
;	CALL	    D5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    D5_L_LOOP	
;	RETURN	
;CS5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    CS5_L_LOOP
;	RETURN	
;CS5_L_LOOP
;	CALL	    CS5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    CS5_L_LOOP	
;	RETURN	
;C5_L
;	MOVLW	    002H
;	MOVWF	    MY_CNT4
;	CALL	    C5_L_LOOP
;	RETURN	
;C5_L_LOOP
;	CALL	    C5
;	DECFSZ	    MY_CNT4,F	
;	GOTO	    C5_L_LOOP	
;	RETURN		

B5
	MOVLW	    006H
	MOVWF	    MY_CNT1
	MOVLW	    00AH
	MOVWF	    MY_CNT2
	CALL	    B1_LOOP
	CALL	    B2_LOOP
	NOP
	NOP
	RETURN	
B1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    B1_LOOP	
	RETURN	
B2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    B2_LOOP	
	RETURN	
B3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    B3_LOOP	
	RETURN	
	
AS5
	MOVLW	    000H
	MOVWF	    MY_CNT1
	MOVLW	    00BH
	MOVWF	    MY_CNT2
	CALL	    AS1_LOOP
	CALL	    AS2_LOOP
	RETURN	
AS1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    AS1_LOOP	
	RETURN	
AS2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    AS2_LOOP	
	RETURN	
AS3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    AS3_LOOP	
	RETURN	
	
A5
	MOVLW	    00AH
	MOVWF	    MY_CNT1
	MOVLW	    00BH
	MOVWF	    MY_CNT2
	CALL	    A1_LOOP
	CALL	    A2_LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN	
A1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    A1_LOOP	
	RETURN	
A2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    A2_LOOP	
	RETURN	
A3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    A3_LOOP	
	RETURN	
	
GS5
	MOVLW	    005H
	MOVWF	    MY_CNT1
	MOVLW	    00CH
	MOVWF	    MY_CNT2
	CALL	    GS1_LOOP
	CALL	    GS2_LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN	
GS1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    GS1_LOOP	
	RETURN	
GS2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    GS2_LOOP	
	RETURN	
GS3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    GS3_LOOP	
	RETURN	
	
G5
	MOVLW	    001H
	MOVWF	    MY_CNT1
	MOVLW	    00DH
	MOVWF	    MY_CNT2
	CALL	    G1_LOOP
	CALL	    G2_LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN	
G1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    G1_LOOP	
	RETURN	
G2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    G2_LOOP	
	RETURN	
G3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    G3_LOOP	
	RETURN		
	
FS5
	MOVLW	    00EH
	MOVWF	    MY_CNT1
	MOVLW	    00DH
	MOVWF	    MY_CNT2
	CALL	    FS1_LOOP
	CALL	    FS2_LOOP
	RETURN	
FS1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    FS1_LOOP	
	RETURN	
FS2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    FS2_LOOP	
	RETURN	
FS3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    FS3_LOOP	
	RETURN	
	
F5
	MOVLW	    00BH
	MOVWF	    MY_CNT1
	MOVLW	    00EH
	MOVWF	    MY_CNT2
	CALL	    F1_LOOP
	CALL	    F2_LOOP
	NOP
	NOP
	NOP
	RETURN	
F1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    F1_LOOP	
	RETURN	
F2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    F2_LOOP	
	RETURN	
F3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    F3_LOOP	
	RETURN	
	
E5
	MOVLW	    009H
	MOVWF	    MY_CNT1
	MOVLW	    00FH
	MOVWF	    MY_CNT2
	CALL	    E1_LOOP
	CALL	    E2_LOOP
	NOP
	NOP
	NOP
	RETURN	
E1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    E1_LOOP	
	RETURN	
E2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    E2_LOOP	
	RETURN	
E3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    E3_LOOP	
	RETURN	
	
DS5
	MOVLW	    008H
	MOVWF	    MY_CNT1
	MOVLW	    010H
	MOVWF	    MY_CNT2
	CALL	    DS1_LOOP
	CALL	    DS2_LOOP
	RETURN	
DS1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    DS1_LOOP	
	RETURN	
DS2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    DS2_LOOP	
	RETURN	
DS3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    DS3_LOOP	
	RETURN	
	
D5
	MOVLW	    007H
	MOVWF	    MY_CNT1
	MOVLW	    011H
	MOVWF	    MY_CNT2
	CALL	    D1_LOOP
	CALL	    D2_LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN	
D1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    D1_LOOP	
	RETURN	
D2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    D2_LOOP	
	RETURN	
D3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    D3_LOOP	
	RETURN	
	
CS5
	MOVLW	    008H
	MOVWF	    MY_CNT1
	MOVLW	    012H
	MOVWF	    MY_CNT2
	CALL	    CS1_LOOP
	CALL	    CS2_LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN	
CS1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    CS1_LOOP	
	RETURN	
CS2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    CS2_LOOP	
	RETURN	
CS3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    CS3_LOOP	
	RETURN	
	
C5
	MOVLW	    00AH
	MOVWF	    MY_CNT1
	MOVLW	    013H
	MOVWF	    MY_CNT2
	CALL	    C1_LOOP
	CALL	    C2_LOOP
	NOP
	RETURN	
C1_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    C1_LOOP	
	RETURN	
C2_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    C2_LOOP	
	RETURN	
C3_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    C3_LOOP	
	RETURN	
	
C6
	MOVLW	    00CH
	MOVWF	    MY_CNT1
	MOVLW	    009H
	MOVWF	    MY_CNT2
	CALL	    C1_H_LOOP
	CALL	    C2_H_LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	RETURN	
C1_H_LOOP
	CALL	    TIME1
	DECFSZ	    MY_CNT1,F	
	GOTO	    C1_H_LOOP	
	RETURN	
C2_H_LOOP
	CALL	    TIME2
	DECFSZ	    MY_CNT2,F	
	GOTO	    C2_H_LOOP	
	RETURN	
C3_H_LOOP
	CALL	    TIME3
	DECFSZ	    MY_CNT3,F	
	GOTO	    C3_LOOP	
	RETURN	
	
D5_32
	MOVLW	    00CH
	MOVWF	    MY_CNT9
	CALL	    D5_32_LOOP
	RETURN	
D5_32_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    D5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    D5	    
	DECFSZ	    MY_CNT9,F
	GOTO	    D5_32_LOOP	
	RETURN	

A5_32
	MOVLW	    012H
	MOVWF	    MY_CNT9
	CALL	    A5_32_LOOP
	RETURN	
A5_32_LOOP
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    A5
	MOVLW	    B'00000001'	
	MOVWF	    PORTB
	CALL	    A5	    
	DECFSZ	    MY_CNT9,F
	GOTO	    A5_32_LOOP	
	RETURN	
	
DELAY_16
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	MOVLW	    02AH
	MOVWF	    MY_CNT7
	CALL	    DELAY_16_LOOP
	RETURN	
DELAY_16_LOOP
	DECFSZ	    MY_CNT7,F	
	GOTO	    TIME3	
	RETURN

DELAY_8
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	MOVLW	    002H
	MOVWF	    MY_CNT8
	CALL	    DELAY_8_LOOP
	RETURN	
DELAY_8_LOOP
	DECFSZ	    MY_CNT8,F	
	GOTO	    DELAY_16	
	RETURN

DELAY_4
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	MOVLW	    002H
	MOVWF	    MY_CNT9
	CALL	    DELAY_4_LOOP
	RETURN	
DELAY_4_LOOP
	DECFSZ	    MY_CNT9,F	
	GOTO	    DELAY_8	
	RETURN	
	
TIME1
	MOVLW	    04H
	MOVWF	    CNT1			
LOOP1  
	DECFSZ	    CNT1,F	
	GOTO	    LOOP1			
	RETURN
	
TIME2
	MOVLW	    0CH
	MOVWF	    CNT2	
LOOP2
	CALL	    TIME1
	DECFSZ	    CNT2,F	
	GOTO	    LOOP2	
	RETURN	

TIME3
	MOVLW	    028H
	MOVWF	    CNT3			
LOOP3
	CALL	    TIME2
	DECFSZ	    CNT3,F	
	GOTO	    LOOP3	
	RETURN	

MYTIMEOUT1
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	MOVLW	    002H
	MOVWF	    MY_CNT9
	CALL	    MYTIMEOUT_LOOP
	RETURN	
MYTIMEOUT_LOOP
	DECFSZ	    MY_CNT9,F	
	GOTO	    DELAY_16	
	RETURN	
	
MYTIMEOUT2
	MOVLW	    B'00000000'	
	MOVWF	    PORTB
	CALL	    DELAY_16
	RETURN	
	
	END