    LIST P = PIC16F84A
    INCLUDE "P16F84A.INC"

    __CONFIG _HS_OSC
    
    ORG 0H
MAIN 
    BSF STATUS, RP0
    CLRF TRISB
    BCF STATUS,RP0
    CLRF PORTB
    BCF PORTB, 0
    BSF PORTB, 1
    BCF PORTB, 2
    BSF PORTB, 3
    BCF PORTB, 4
    BSF PORTB, 5
    BCF PORTB, 6
    BSF PORTB, 7
    END